name: SneakyNPCs
version: "1.0"
main: com.danidipp.sneakynpcs.SneakyNPCs
api-version: "1.21"
authors:
  - DaniDipp
description: "Paper plugin for managing NPC GUIs"
dependencies:
  server:
    MagicSpells:
      load: BEFORE
      required: true
    CoreProtect:
      load: BEFORE
      required: false
    SneakyMannequins:
      load: BEFORE
      required: false
